### ISSUE TITLE
docker-compose up fails on step 10/10

### ISSUE THREAD

**Issue by stefanwright1988** [nSoft-team/glassbox-nodejs-starter#3]
Sys info:
Macbook Pro M1 2021
Node version 16.17.0
VSCode

Error output:
```
=> ERROR [glassbox-nodejs-starter-2a9f7206b928f9e5683077aa35e3e8a55ea99abf_cassandra-web 10/10] RUN npm run build:cassandra-web               2.6s
------
 > [glassbox-nodejs-starter-2a9f7206b928f9e5683077aa35e3e8a55ea99abf_worker internal] load build context:
------
------
 > [glassbox-nodejs-starter-2a9f7206b928f9e5683077aa35e3e8a55ea99abf_user internal] load build context:
------
------
 > [glassbox-nodejs-starter-2a9f7206b928f9e5683077aa35e3e8a55ea99abf_cassandra-web 10/10] RUN npm run build:cassandra-web:
#0 0.592 
#0 0.592 > glassbox-mc@1.0.0 build:cassandra-web
#0 0.592 > tsc -b packages/cassandra-web
#0 0.592 
#0 2.522 packages/cassandra-web/src/app.ts(2,24): error TS7016: Could not find a declaration file for module 'base'. '/glassbox-ms/packages/base/dist/index.js' implicitly has an 'any' type.
#0 2.522   Try `npm i --save-dev @types/base` if it exists or add a new declaration (.d.ts) file containing `declare module 'base';`
------
failed to solve: executor failed running [/bin/sh -c npm run build:cassandra-web]: exit code: 1
```

**Comment by VladislavTsygankov** [comment]
Hi! As I said before u can pull new version. Or u can delete file `tsconfig.tsbuildinfo` and dist/ folder.
After u can run it again.

**Comment by simonl65** [comment]
Unfortunately this is still happening for me with the latest pull from master. I'm on Windows.

When doing `docker-compose up` I see the following near the end of the process:
```
starter-project-user | src/app.ts(2,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
starter-project-user | src/authentication/strategy.ts(3,22): error TS2307: Cannot find module 'base/dist/models/user' or its corresponding type declarations.
starter-project-user | src/authentication/strategy.ts(17,16): error TS7006: Parameter 'user' implicitly has an 'any' type.
starter-project-user | src/authentication/strategy.ts(24,17): error TS7006: Parameter 'err' implicitly has an 'any' type.
starter-project-user | src/db-connection.ts(1,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
starter-project-user | src/services/user-service.ts(1,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
starter-project-user exited with code 2
```

This issue appears to affect each of the worker, user and cassandra-web packages.

**Comment by simonl65** [comment]
I think this is related to issue #4 ;)

**Comment by simonl65** [comment]
```
starter-project-cassandra-web | /glassbox-ms/packages/cassandra-web/node_modules/ts-node/src/index.ts:859
starter-project-cassandra-web |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
starter-project-cassandra-web |            ^
starter-project-cassandra-web | TSError: ⨯ Unable to compile TypeScript:
starter-project-cassandra-web | src/app.ts(2,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
starter-project-cassandra-web |
starter-project-cassandra-web |     at createTSError (/glassbox-ms/packages/cassandra-web/node_modules/ts-node/src/index.ts:859:12)
starter-project-cassandra-web |     at reportTSError (/glassbox-ms/packages/cassandra-web/node_modules/ts-node/src/index.ts:863:19)
starter-project-cassandra-web |     at getOutput (/glassbox-ms/packages/cassandra-web/node_modules/ts-node/src/index.ts:1077:36)
starter-project-cassandra-web |     at Object.compile (/glassbox-ms/packages/cassandra-web/node_modules/ts-node/src/index.ts:1433:41)
starter-project-cassandra-web |     at Module.m._compile (/glassbox-ms/packages/cassandra-web/node_modules/ts-node/src/index.ts:1617:30)
starter-project-cassandra-web |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
starter-project-cassandra-web |     at Object.require.extensions.<computed> [as .ts] (/glassbox-ms/packages/cassandra-web/node_modules/ts-node/src/index.ts:1621:12)
starter-project-cassandra-web |     at Module.load (node:internal/modules/cjs/loader:997:32)
starter-project-cassandra-web |     at Function.Module._load (node:internal/modules/cjs/loader:838:12)
starter-project-cassandra-web |     at Module.require (node:internal/modules/cjs/loader:1021:19) {
starter-project-cassandra-web |   diagnosticCodes: [ 2307 ]
starter-project-cassandra-web | }
starter-project-cassandra-web | [nodemon] app crashed - waiting for file changes before starting...
starter-project-worker | /glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:859
starter-project-worker |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
starter-project-worker |            ^
starter-project-worker | TSError: ⨯ Unable to compile TypeScript:
starter-project-worker | src/index.ts(2,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
starter-project-worker |
starter-project-worker |     at createTSError (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:859:12)
starter-project-worker |     at reportTSError (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:863:19)
starter-project-worker |     at getOutput (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:1077:36)
starter-project-worker |     at Object.compile (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:1433:41)
starter-project-worker |     at Module.m._compile (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:1617:30)
starter-project-worker |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
starter-project-worker |     at Object.require.extensions.<computed> [as .ts] (/glassbox-ms/packages/worker/node_modules/ts-node/src/index.ts:1621:12)
starter-project-worker |     at Module.load (node:internal/modules/cjs/loader:997:32)
starter-project-worker |     at Function.Module._load (node:internal/modules/cjs/loader:838:12)
starter-project-worker |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
starter-project-worker |   diagnosticCodes: [ 2307 ]
starter-project-worker | }
starter-project-worker | [nodemon] app crashed - waiting for file changes before starting...
starter-project-user | /glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:859
starter-project-user |     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
starter-project-user |            ^
starter-project-user | TSError: ⨯ Unable to compile TypeScript:
starter-project-user | src/app.ts(2,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
starter-project-user |
starter-project-user |     at createTSError (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:859:12)
starter-project-user |     at reportTSError (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:863:19)
starter-project-user |     at getOutput (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:1077:36)
starter-project-user |     at Object.compile (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:1433:41)
starter-project-user |     at Module.m._compile (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:1617:30)
starter-project-user |     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
starter-project-user |     at Object.require.extensions.<computed> [as .ts] (/glassbox-ms/packages/user/node_modules/ts-node/src/index.ts:1621:12)
starter-project-user |     at Module.load (node:internal/modules/cjs/loader:997:32)
starter-project-user |     at Function.Module._load (node:internal/modules/cjs/loader:838:12)
starter-project-user |     at Module.require (node:internal/modules/cjs/loader:1021:19) {
starter-project-user |   diagnosticCodes: [ 2307 ]
starter-project-user | }
starter-project-user | [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by VladislavTsygankov** [comment]
To quick fix run `npm run build:base` then run `docker-compose up` should help.
Later I'll fix script for production start

**Comment by simonl65** [comment]
Unfortunately it's still not working. I'm still seeing the same TSError:
![image](https://user-images.githubusercontent.com/14094202/189156087-c80f6fae-7cad-4d4d-9464-3c4374e6c978.png)

**Comment by nadavl** [comment]
@simonl65 could you pull and try again? Some fixes were made which we believe should solve this one.

**Comment by simonl65** [comment]
Still failing:
```
cassandra-web            |
cassandra-web            | > cassandra@1.0.0 prod
cassandra-web            | > npm run prod:base && tsc && node dist/index.js
cassandra-web            |
cassandra-web            |
cassandra-web            | > cassandra@1.0.0 prod:base
cassandra-web            | > tsc -b ../base
cassandra-web            |

...

cassandra-web            | src/app.ts(2,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
glassbox-ms-kafka-1      | [2022-09-12 08:07:59,422] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
cassandra-web exited with code 2

...

worker                   | src/db-connection.ts(2,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
worker                   | src/index.ts(2,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
worker                   | src/services/kafka-consumer.ts(1,28): error TS2307: Cannot find module 'base' or its corresponding type declarations.
worker                   | src/services/user-service.ts(1,36): error TS2307: Cannot find module 'base' or its corresponding type declarations.
worker exited with code 2
user                     | src/app.ts(2,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
user                     | src/authentication/strategy.ts(3,22): error TS2307: Cannot find module 'base/dist/models/user' or its corresponding type declarations.
user                     | src/authentication/strategy.ts(17,16): error TS7006: Parameter 'user' implicitly has an 'any' type.
user                     | src/authentication/strategy.ts(24,17): error TS7006: Parameter 'err' implicitly has an 'any' type.
user                     | src/db-connection.ts(1,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
user                     | src/services/user-service.ts(1,24): error TS2307: Cannot find module 'base' or its corresponding type declarations.
user exited with code 2
```

**Comment by VladislavTsygankov** [comment]
@simonl65  Could you please write a node version on your's PC?

**Comment by simonl65** [comment]
@VladislavTsygankov I have tried this with both v14.16.1 and v16.17.0

**Comment by nadavl** [comment]
@simonl65 thanks. Is that windows 10?
Are you running with WSL / 2.0? Or just windows terminal?

**Comment by simonl65** [comment]
@nadavl Yes, Windows 10 with Windows Terminal. I have Docker Desktop running with WSL2 also.

**Comment by simonl65** [comment]
I've now treid doing `tsc -b packages/base` manually (working dir is glassbox-ms): nothing gets built and there are no errors.

I then tried again from `glassbox-ms\packages\base` and get the following error:
```
error TS5083: Cannot read file 'C:/Users/Public/Documents/_TUTS/Glassbox/glassbox-ms/packages/base/packages/base/tsconfig.json'.
```

If I then do `tsc` in glassbox-ms/packages/base it does build.

**Comment by simonl65** [comment]
BTW: I'm using tsc --version Version 4.8.2

**Comment by simonl65** [comment]
Manually running `tsc -p ./packages/base/tsconfig.json` does the build :-)

**Comment by nadavl** [comment]
Happy to hear that!
Thanks for the feedback and testing this @simonl65
